### ISSUE TITLE
Killaura bypass

### ISSUE THREAD

**Issue by Animationking11** [DemonDxv/Anticheat-Open-Source#5]
Video: https://user-images.githubusercontent.com/60802108/148610606-eb453bfb-7f1b-4545-97c4-d4093164467c.mp4

Settings:
![MxcX4tUK](https://user-images.githubusercontent.com/60802108/148610718-68648a9a-d64b-406a-b989-4aa7df5cb526.gif)
 

Client: Rise

**Comment by DemonDxv** [comment]
This is an open source anticheat on spigot, I'm not going out of my way to patch every single killaura. Also I do not have this client to test to detect, and therefore I am most likely not going to patch it unless I make something to patch another killaura and happens to patch their aura (and its a paid client) + some aura checks don't work unless your attacking a player and they are taking damage..
