### ISSUE TITLE
What the duck

### ISSUE THREAD

**Issue by Briiqn** [DemonDxv/Anticheat-Open-Source#8]
Funny ->  https://github.com/DemonDxv/Anticheat-Open-Source/blob/main/src/main/java/me/rhys/anticheat/checks/movement/sneak/SneakD.java

The given Java code is not optimal because it has redundant and error-prone logic. The if and else if statements check whether the action in the packet is either START_SNEAKING or STOP_SNEAKING. However, the same code block is executed for both conditions. This means that the sneakTicks variable will be incremented regardless of the action type. Therefore, the code is unnecessarily repetitive and makes it harder to maintain and understand. Additionally, if another action is added in the future, the code would need to be updated to handle the new case. A better approach would be to consolidate the conditions and only increment the sneakTicks variable when the player starts or stops sneaking.

![image](https://user-images.githubusercontent.com/82249811/222937977-a3d6e006-40c8-4af3-9ad4-1d0078024591.png)

**Comment by DemonDxv** [comment]
Thank you for pointing out a years old code that I half assed with multiple useless, purposeful issues, bypasses, bugs, and redundant things. I am working on a v2 of this that will be a lot more cleaner and more effective and efficient. Thanks for the bug report tho (won't be getting fixed or modified as the project is discontinued and is no longer being updated) :joy:
